### PR TITLE
Recreate Kibana on upgrade

### PR DESCRIPTION
**Pull request by anders-swanson**
We recreate kibana on upgrade, since kibana does not support a rolling upgrade. If multiple kibana versions are running you may have a data race and subsequent data corruption.

### CODE REVIEW

**Comment by gilbode** [comment]
This seems like it will result in downtime anytime the kibana deployment is rolled out, not just for kibana version upgrades.  Any idea how much downtime & what other circumstances besides upgrade of verrazzano this would happen?

Also - this is fixing a bug.  We somehow need a test for this.

**Comment by anders-swanson** [comment]
> This seems like it will result in downtime anytime the kibana deployment is rolled out, not just for kibana version upgrades. Any idea how much downtime & what other circumstances besides upgrade of verrazzano this would happen?
> 
> Also - this is fixing a bug. We somehow need a test for this.

- Yes, it will result in downtime. About 30-60 seconds for Kibana. We could potentially mitigate this for changes that do not require a recreate by dynamically selecting the Strategy: Only use recreate if the Kibana image is changing. 
- Testing that Recreate is set as the strategy during an upgrade is probably sufficient

**Comment by gilbode** [comment]
> * Testing that Recreate is set as the strategy during an upgrade is probably sufficient

Can you please add a unit test to this PR that tests that?

**Comment by anders-swanson** [comment]
Added tests and set to use recreate only if Kibana image is changing.

**Review by gilbode — APPROVED** [review]

**Comment by bobdonat** [comment]
same comment as other PR - I think a description of the change would be useful

**Review by michael-cico — APPROVED** [review]

**Pull request merged**
